# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gelina/igl

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  script:
    - cd BuildUs/build_fold
    - cmake ..
    - make
  artifacts:
    paths:
      - BuildUs
      - tests/buildtests
     

# run tests using the binary built before
test:
  stage: test
  script:
    - ./BuildUs/build_fold/tests/buildtests
