
build_images:
  image: docker:19.03.1
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.1-dind
  stage: build
  script:
    - cd orchestrus
    - docker login -u gelina -p $DOCKER_HUB_GELINA
    - docker build worker -t gelina/worker
    - docker push gelina/worker
    - docker build bdd-controller -t gelina/bdd-controller
    - docker push gelina/bdd-controller


